[application]
loop_frequency = 600
timer_frequency = 60
display_frequency = 60
audio_frequency = 440
window_width = 800
window_height = 600
foreground_color = 0xFFFFFF
background_color = 0x000000

[memory]
reserved_end = 0x200
program_end = 0x1000
reserved_read_only = true

[display]
width = 64
height = 32
default_mode = "hires"

[quirks]
vf_reset = false                    # Whether logical operations (AND, OR, XOR) reset VF
index_increment = false             # Whether FX55 and FX65 (reading or writing registers to memory) increments register I
display_clipping = false            # Whether sprites are clipped or wrap around
vy_shifting = false                 # Whether shift operations use Vy
vx_jumping = false                  # Whether jump operation uses Vx
clear_on_mode_change = true         # Whether changing the resolution mode clears the display
vf_collision_counter = false        # Does the VF register act as a counter or as a flag when drawing
lores_whole_pixel_scrolling = false # Whether scrolling in lores mode scrolls by whole pixels or by half pixels
loresSpriteHandling = "draw_wide"   # How hires sprites are handled in lores mode: "draw_wide" - 16x16, "draw_tall" - 8x16, or "no_operation"

[keymap]
0 = "X"
1 = "1"
2 = "2"
3 = "3"
4 = "Q"
5 = "W"
6 = "E"
7 = "A"
8 = "S"
9 = "D"
A = "Z"
B = "C"
C = "4"
D = "R"
E = "F"
F = "V"
