name: Build, Analyze and Test

on: 
  push:
    branches:
      - main
      - ci-matrix
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }}

      - name: Build
        run: cmake --build build

      - uses: actions/upload-artifact@v4
        with:
          name: compiled-build-${{ matrix.os }}
          path: build/

  build-wasm:
    name: Build for WebAssembly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: emscripten-core/setup-emsdk@v15
        with: 
          version: 6.0.9
          actions-cache-folder: 'emsdk-cache'

      - name: Configure CMake
        run: emcmake cmake -S . -B build-wasm

      - name: Build
        run: cmake --build build-wasm

  static-analysis:
    name: Run Clang-Tidy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-ubuntu-latest
          path: build/

      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

      - name: Install Clang-Tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Run Clang-Tidy
        run: run-clang-tidy -p build

  dynamic-analysis:
    name: Run Valgrind
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-ubuntu-latest
          path: build/

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Run Valgrind
        run: |
          chmod +x build/tests/run_tests
          valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/tests/run_tests

  tests:
    name: Run Tests
    needs: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-${{ matrix.os }}
          path: build/

      - name: Run Tests (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x build/tests/run_tests
          ./build/tests/run_tests

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        run: .\build\tests\Debug\run_tests.exe
