name: Build, Analyze and Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - uses: actions/upload-artifact@v4
        with:
          name: compiled-build-folder
          path: build/

  static-analysis:
    name: Run Clang-Tidy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-folder
          path: build/

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy && sudo apt-get install -y libsdl2-dev

      - name: Run Clang-Tidy
        run: run-clang-tidy -p build

  dynamic-analysis:
    name: Run Valgrind
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-folder
          path: build/

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Run Valgrind
        run: |
          chmod +x build/tests/run_tests
          valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./build/tests/run_tests

  tests:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: compiled-build-folder
          path: build/

      - name: Run Tests
        run: |
          chmod +x build/tests/run_tests
          ./build/tests/run_tests
